apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ampkeda2
  region: us-west-2
  version: '1.30'
#iam:
#  withOIDC: true
managedNodeGroups:
- name: default-ng
  minSize: 1
  maxSize: 3
  desiredCapacity: 2
  labels: {role: mngworker}
  iam:
    withAddonPolicies:
      certManager: true
      cloudWatch: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
